package.json, src/crowdstrike/FalconAPIClient.test.ts, src/crowdstrike/FalconAPIClient.ts, src/crowdstrike/__recordings__/executeAPIRequest429_945518834/recording.har, src/crowdstrike/__recordings__/makeRequest429_3698051257/recording.har, src/crowdstrike/types.ts, yarn.lock
Please let me know if there are scenarios that should be tested. I can think of a few, but I figure smaller PRs when possible is a Good Thing.
=> Respect rate limit headers

package.json, src/index.ts, src/jupiterone/converters.test.ts, src/jupiterone/converters.ts, src/steps/fetchDevicePolicyRelationships.ts, src/steps/fetchDevices.ts, src/steps/fetchPreventionPolicies.ts, src/steps/prepareAccount.ts, tools/execute.ts, yarn.lock
Moving to the latest stuff, starting with the SDK here, and then will need to update the deployment project to use the latest tools and failure handling.
=> Update integration SDK

CHANGELOG.md, src/jupiterone/converters.test.ts, src/jupiterone/converters.ts, src/steps/fetchDevices.ts
In favor of a managed mapping rule
=> Remove `crowdstrike_sensor` `PROTECTS` `user_endpoint` relationship

CHANGELOG.md, package.json, src/crowdstrike/FalconAPIClient.test.ts, src/crowdstrike/FalconAPIClient.ts
```
- Improved waiting logic after encountering 429 errors
=> Improve waiting logic after encountering 429 errors

docs/jupiterone.md, package.json, yarn.lock
Fixing package.json to use peerDependencies for integration-sdk-core to avoid exception thrown to Sentry.
=> fixing package.json to use peerDependencies for integration-sdk-core

CHANGELOG.md, package.json, src/jupiterone/converters.ts, yarn.lock
Required a converter to be updated with the _key property.
=> Update sdk-* packages from v7 to v8.2.1

src/crowdstrike/FalconAPIClient.ts, src/crowdstrike/types.ts, src/steps/fetchVulnerabilities.ts
- Enable "after" pagination cursor
- Add pagination logging to verify pagination is working correctly.
- Limited ingest to last successful run or last 10 days
=> Int 342 update pagination

CHANGELOG.md, package.json, src/steps/fetchVulnerabilities.ts
Contains a single char change to fix a pagination query.
=> Release v2.1.4 

CHANGELOG.md, package.json
Release 2.1.7 adding `code-ql` workflow, `questions` workflow, and managed questions.
=> Release 2.1.7

.github/workflows/gitleaks.yml, CHANGELOG.md, package.json, src/jupiterone/converters.test.ts, src/jupiterone/converters.ts, yarn.lock
`crowdstrike_sensor`'s should map to `aws_instance` entities when the
CrowdStrike device's `service_provider` property has the value `AWS_EC2_V2`
=> INT-4413 - Fix `crowdstrike_sensor` `aws_instance` mapping

src/crowdstrike/FalconAPIClient.ts, src/steps/fetchDevicePolicyRelationships.ts, src/steps/fetchVulnerabilities.ts
This PR makes a couple of small improvements to the project.
- End use of `await` for `hasKey` operations
- Increase page size to 250 for vulnerability step
- I plan to continue to increase the page size slowly until we
hit the max of 5000 assuming all goes well.
- return immediately after `abort` in `retry`. Not returning logs
that error is possibly recoverable when it is not.
=> update: small fixes, increase page size

package.json, src/config.ts, src/crowdstrike/getOrCreateFalconAPIClient.ts, src/index.ts, src/steps/account/index.ts, src/steps/constants.ts, src/steps/devicePolicies/index.ts, src/steps/devices/index.ts, src/steps/index.ts, src/steps/preventionPolicies/index.ts, src/steps/utils.ts, src/steps/vulnerabilities/index.ts, src/validateInvocation.test.ts, test/integrationInstanceConfig.ts, yarn.lock
- chore: rename integrationconfig, update patterns
- unexport execution handlers
- move utils into seperate file
- remove unused imports
=> Code cleanup and organization

src/config.ts, src/steps/vulnerabilities/index.ts, src/steps/vulnerabilities/util.test.ts, src/steps/vulnerabilities/util.ts, src/validateInvocation.test.ts
This PR adds the ability to filter Vulnerabilities based on vulnerability severity and if the vulnerability is open or closed.
=> [INT-4860] Add Vulnerabilities Filter

src/crowdstrike/types.ts, src/jupiterone/converters.test.ts, src/jupiterone/converters.ts
This PR updates the CrowdStrike Vulnerabilities to be inline with the [Vulnerability Data Model](https://github.com/JupiterOne/data-model/blob/main/src/schemas/Vulnerability.json).
=> Add fields to CrowdStrike Vulnerabilities

src/steps/vulnerabilities/util.test.ts, src/steps/vulnerabilities/util.ts
- change defaults
- update tests
=> int 5220 increase defaults

CHANGELOG.md, package.json
=> Release 3.0.1

CHANGELOG.md, package.json
=> Release 3.0.2

src/steps/vulnerabilities/util.test.ts, src/steps/vulnerabilities/util.ts
- setting defaults after two week period
- update tests
=> int 5220 set defaults

CHANGELOG.md, package.json
=> Release 3.0.3

CHANGELOG.md, package.json, src/jupiterone/converters.test.ts, src/jupiterone/converters.ts, src/steps/vulnerabilities/index.ts
Adding `exprtRating` and `exploitStatus` properties. Raising vuln limit to 400.
=> add exploitStatus add exprtRating

.github/workflows/codeql-analysis.yml, src/config.ts, src/steps/devices/index.ts, src/steps/vulnerabilities/index.ts
Add config options for page size. Planning to release as a beta.
=> INT-6268-add-config-options

package.json, yarn.lock
Update j1 dependencies to keep them up to date
=> Int 7516 dependencies update

src/crowdstrike/FalconAPIClient.ts
This in part of a series of prs to improve the speed in which we fetch/process vulnerabilities.
Logs request time in debug mode, to understand how much it takes per request.
=> INT-7939: improvements (2) - Log request times

package.json
#Description:
missing postversion hook causing build to fail.
=> INT-7669: adding postversion hook

.github/workflows/integration-deployment.yml
#Description: 
added releaseNotes property to j1 action
=> INT-7669: including release notes property

src/crowdstrike/FalconAPIClient.ts, src/steps/zero-trust-assessment/index.ts
Added catch for 403 - reduced chunk size - only ingest scores less than 50
=> Fixes to zta step 

src/crowdstrike/FalconAPIClient.ts
Log the body of any 400 response so that we can use that to better understand the issue
=> Added log of body for when 400 happens

src/config.ts, src/steps/vulnerabilities/index.ts, src/validateInvocation.test.ts
- feat: add new config fields for controlling vulnerabilities days in past
- fix tests
=> Add vulnerabilitiesMaxDaysInPast Config Field
